### ISSUE TITLE
Support changing first day of the week

### ISSUE THREAD

**Issue by lalnuo** [react-component/calendar#107]
Starting week from monday (or any other day) would be nice.

**Comment by yiminghe** [comment]
```
const now = new GregorianCalendar(locale);
now.setTime(Date.now());
```

provide you locale to init  GregorianCalendar and pass it to Calendar https://github.com/yiminghe/gregorian-calendar/blob/master/src/locale/zh_CN.js#L9

**Comment by lalnuo** [comment]
Thank you!

**Comment by Twisterking** [comment]
I am sorry but your answer confuses me @yiminghe.
So what I would do is the following??
```
const GregorianCalendar = require('gregorian-calendar');
const myLoc = new GregorianCalendar({
  timezoneOffset: 1 * 60, // I am in GMT+1
  firstDayOfWeek: 1,
  minimalDaysInFirstWeek: 1
});
ReactDOM.render(<Calendar locale={myLoc} />, container);
```

is this correct?

**Comment by yiminghe** [comment]
the new api is based on moment, checkout moment docs @Twisterking
