### ISSUE TITLE
如何按需自定义打包 ？

### ISSUE THREAD

**Issue by liaobin312716** [react-component/calendar#109]
只能使用 rc-tools 打包么？ 如何自己打包， 比如原有项目已经在使用react , classnames ,等库 ， 如何打包时将react , 等依赖不打包进去， 打包成umd 的方式 ， 将 react 变成外部依赖，有什么办法么 ？

**Comment by yiminghe** [comment]
npm install rc-calendar  

都是模块，打包查阅 webpack 文档
