### ISSUE TITLE
Long range

### ISSUE THREAD

**Issue by iNikNik** [react-component/calendar#111]
How I can select long date range ? For example - 3 month

**Comment by yiminghe** [comment]
switch the month by arrow....

**Comment by iNikNik** [comment]
I mean if I switch month on the right side - it automatically switches left side. This is really confusing when I've already chosen start date.

**Comment by yiminghe** [comment]
this is conventional.

https://www.google.com.hk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=range%20date%20picker
