### ISSUE TITLE
文档写的好像不是很全呀？

### ISSUE THREAD

**Issue by songguangyu** [react-component/calendar#112]
比如 点x 关闭的事件 没有找到，增加确定按钮的配置没有找到

**Comment by blackpuppy** [comment]
而且，这个到底是做什么的呢？不知道这是真的Calendar呢，还是只是个DateTimePicker？
Calendar是可以放多个事件，添加新的事件，事件可以跨多个日期，等等，比如[FullCalendar](http://fullcalendar.io/)。而DateTimePicker只是选个日期/时间罢了。

**Comment by yiminghe** [comment]
请仔细看下 demo
