### ISSUE TITLE
Can't get value or defaultValue to work

### ISSUE THREAD

**Issue by SachaG** [react-component/calendar#114]
I'm using the calendar for a filtering UI that supports dates in the URL query string (i.e. `http://localhost:3000/?date=2016-04-06`), so I would like to preset the calendar to that date when it's specified. 

Here's what I'm doing: 

```
const currentDate = // get date string from URL
let date = new GregorianCalendar();
date.setTime(moment(currentDate).toDate().getTime());
return (
  <Calendar
    defaultValue={date}
    showDateInput={false}
    showToday={false}
    onChange={this.goToDate}
    formatter="YYYY-MM-DD"
  />
)
```

It doesn't seem to do anything in the calendar component though. I would've expected this would make the date selected?

Also, I'm not sure I understand the difference between `value` and `defaultValue`?

**Comment by afc163** [comment]
http://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by SachaG** [comment]
Oh right, that makes sense. But specifying either `value` or `defaultValue` still doesn't seem to do anything? What's the expected result?

**Comment by benjycui** [comment]
If `value` does not wok as controlled properties, please provide a re-producible demo: http://codepen.io/anon/pen/pgdXYp?editors=001 THX!

**Comment by SachaG** [comment]
Hmm, I'm not sure how I can use the [Gregorian Calendar](https://github.com/yiminghe/gregorian-calendar) package with CodePen? It seems like it's the only way to specify a `defaultValue`?

**Comment by benjycui** [comment]
Maybe you can try http://www.webpackbin.com/4ykHG3QZW

**Comment by modomodo** [comment]
:+1: I'm also facing the same issue using RangeCalendar

**Comment by SachaG** [comment]
I think maybe I misunderstood what `defaultValue` does. I'm able to set it correctly as a `prop` of the calendar, but what I actually want to do is to control which day is marked as selected (using the `rc-calendar-selected-day` class). 

So for example, if I access the `/?date=2016-06-10` URL, then "June 10, 2016" would be marked as selected in the calendar. And if I clear that URL parameter, the calendar would also reflect that and clear the selection.

I originally thought I could use `value` or `defaultValue` to achieve this, but neither one works. Any tips on how I can do it?

**Comment by yiminghe** [comment]
selectedValue, defaultSelectedValue

**Comment by SachaG** [comment]
Thanks, `selectedValue` worked!

**Comment by shyam528** [comment]
How you solved it @SachaG . Can you please help me.
I have a value let say '2017-08-05', I want that when we open calendar this value should be select by default. I have tried with  selectedValue it's not working, Please help

**Comment by SachaG** [comment]
Sorry, I'm not using this component anymore. I switched to https://github.com/YouCanBookMe/react-datetime
