### ISSUE TITLE
Default Close button for RangeCalendar has its tooltip in Chinese

### ISSUE THREAD

**Issue by modomodo** [react-component/calendar#116]
As stated in the title, the default tooltip is in chinese for the close button. This occurs when not passing any prop for locale and allowing it to be the default of en_us.

The code:
![image](https://cloud.githubusercontent.com/assets/5679726/15650290/2ae2f212-2680-11e6-851c-c3b035c5e4de.png)

The screenshot:
![image](https://cloud.githubusercontent.com/assets/5679726/15650300/3e931da0-2680-11e6-8434-c4c3304a5420.png)

The relevant prop:
![image](https://cloud.githubusercontent.com/assets/5679726/15650447/4c3f6dea-2681-11e6-8f5c-524f44835104.png)

It would be great to have consistency for English throughout to enable a wider audience for the component. I love the component btw!

**Comment by yiminghe** [comment]
If you do not pass any locale to RangeCalendar, the title is 'Clear', please check your code

https://github.com/react-component/calendar/blob/db92ee4c9935b6cf6660700b57e9d03fa094039b/src/RangeCalendar.js#L269
