### ISSUE TITLE
RangeCalendar should have the option of disabling DateInput

### ISSUE THREAD

**Issue by modomodo** [react-component/calendar#118]
I'm currently trying to disable the DateInput for a range calendar and even passed in the Calendar prop:
```js
<RangeCalendar
    dateInputPlaceholder={['Start Date', 'End Date']}
    defaultSelectedValue={[prevMonth, now]}
    showDateInput={false}
 />
```

However, this doesn't work with the RangeCalendar. It would really be neat if the same functionality of Calendar and its props are applied to RangeCalendar too

**Comment by yiminghe** [comment]
start and end time may be span more than one month, need date input to indicate start and end time

**Comment by yjzzcao** [comment]
But we need custom DateInput, so what do we need to do?
