### ISSUE TITLE
Styling does not work

### ISSUE THREAD

**Issue by sferoze** [react-component/calendar#119]
When I add this package to my app via npm, none of the styling shows up. 

So I downloaded the styles directly from the repository and added to my project but I get error:

`variable @prefixClass is undefined`

Why is the styling not working in the first place. I would just like to add the package and use it. But none of the styling works.

**Comment by modomodo** [comment]
@sferoze If it helps, you can grab the CSS styles from the examples website. That's what I did

**Comment by yiminghe** [comment]
use .css
