### ISSUE TITLE
Extend Calendars to allow setting of timezoneOffset

### ISSUE THREAD

**Issue by modomodo** [react-component/calendar#120]
By default, all the calendars use a timezoneOffset of: `-480`
![image](https://cloud.githubusercontent.com/assets/5679726/15740099/07940dc6-28bc-11e6-8adf-8511c1b2a52b.png)

This is a problem for people in other countries and widely different timezones such as East Africa where the offset is: `180`

Could an optional prop be built into all the calendars allowing the proper setting of timezoneOffset?

**Comment by yiminghe** [comment]
pass timezoneOffset to create new GregorianCalendar value and pass this value to defaultValue of GregorianCalendar

**Comment by yiminghe** [comment]
7.x use moment, see http://react-component.github.io/calendar/examples/antd-calendar.html to set utcOffset
