### ISSUE TITLE
Gregorian Calendar vs Moment

### ISSUE THREAD

**Issue by SachaG** [react-component/calendar#132]
It seems like the [Gregorian Calendar](https://github.com/yiminghe/gregorian-calendar) lib is pretty similar to [Moment](http://momentjs.com/). I was wondering if there was any plans to switch this package to Moment, since it's a more popular and more standard library?

**Comment by yiminghe** [comment]
will change to moment in next version

**Comment by SachaG** [comment]
Oh that's awesome news :)

**Comment by yiminghe** [comment]
7.x
