### ISSUE TITLE
Calendar shows wrong current date

### ISSUE THREAD

**Issue by SachaG** [react-component/calendar#133]
My computer is set to the Japan timezone, and the current selected date (`rc-calendar-today`) is one day behind (i.e. July 14 instead of July 15).

**Comment by SachaG** [comment]
This is how I'm calling the component:

```
<Calendar
          selectedValue={date}
          showDateInput={false}
          showToday={false}
          onSelect={this.goToDate}
          formatter="YYYY-MM-DD"
          disabledDate={(date) => {
            return date.getTime() > moment().add(1, "days").valueOf()
          }}
        />
```

**Comment by yiminghe** [comment]
see examples to set locale, nothing to do with your computer setting

**Comment by SachaG** [comment]
Why do you have to set a locale? Shouldn't it just default to the browser's current timezone?

**Comment by SachaG** [comment]
Another weird thing: the calendar doesn't show the same current date in development and production. Can it be because of the different server timezones?

![https://s3.amazonaws.com/f.cl.ly/items/3x0q2R2R1V0d0J151z1s/Screen%20Shot%202016-07-18%20at%205.23.30%20PM.png?v=30c75b9e](https://s3.amazonaws.com/f.cl.ly/items/3x0q2R2R1V0d0J151z1s/Screen%20Shot%202016-07-18%20at%205.23.30%20PM.png?v=30c75b9e)

**Comment by yiminghe** [comment]
No, calendar has nothing to do with your local setting, I do not use native Date, please check your locale prop

**Comment by SachaG** [comment]
The documentation says locale defaults to `import from 'rc-calendar/lib/locale/en_US'`. I'm fine with displaying the calendar in english, I'm just trying to understand how the calendar sets its own timezone. How does the calendar figure out what the current date is?

**Comment by helloyou2012** [comment]
@SachaG , `en_US ` is `United States Timezone` and you can change locale like that:

```
// Import from US
import enUS from 'rc-calendar/lib/locale/en_US';
// Change timezone for your locale
enUS.timezoneOffset = -(new Date).getTimezoneOffset();
```

**Comment by yiminghe** [comment]
try set defaultValue to correct moment with desired utfOffset in 7.x

http://react-component.github.io/calendar/examples/antd-calendar.html

**Comment by jarstingstall** [comment]
@helloyou2012 is the `enUs.timezoneOffset` API still supported? I tried your suggestion and `rc-calendar-today` class is still applied based on UTC timezone.

**Comment by helloyou2012** [comment]
@jarstingstall not supported currently. As @yiminghe mentioned, you should set `defaultValue` to the moment object with your `locale` and `utcOffset`. It will use the locale and UTC offset of the `defaultValue`.

```jsx
import Calendar from 'rc-calendar';
import moment from 'moment';
import 'moment/locale/zh-cn';

const now = moment();
now.locale('zh-cn').utcOffset(8);

const MyComponent = (props) => (
  <Calendar
    {...props}
    defaultValue={now}
  />
);
```
