### ISSUE TITLE
"Now" is disabled and clicking does not trigger value changes

### ISSUE THREAD

**Issue by fanfank** [react-component/calendar#135]
![image](https://cloud.githubusercontent.com/assets/3654455/17291507/f065a2c4-5816-11e6-945e-6a48eabe49fa.png)

I just go to the example page: http://react-component.github.io/calendar/examples/antd-calendar.html

And find out that the value does not change according to my selection

除非设置defaultValue，否则没办法改变这个情况。昨天看的时候仍然是好的

**Comment by fanfank** [comment]
2016-08-05 01:07:00
此刻，问题复现

**Comment by yiminghe** [comment]
再试下 7.x

**Comment by fanfank** [comment]
好的，我替换成7.x后再观望一下
