### ISSUE TITLE
Should not highlight date cell in unselected date

### ISSUE THREAD

**Issue by afc163** [react-component/calendar#138]
https://github.com/ant-design/ant-design/issues/2711

---

1. do not highlight today when date is empty

   ![](https://zos.alipayobjects.com/rmsportal/fOVjUdHFuKMWMXi.png)

2. do not highlight any date in other panel when date is selected

   ![](https://zos.alipayobjects.com/rmsportal/jpzGgtUXzpfixlz.png)

**Comment by afc163** [comment]
Need to fix in 5.x

**Comment by yiminghe** [comment]
是键盘操作指示日期，不是选中日期
