### ISSUE TITLE
Add support for custom starting day of the week

### ISSUE THREAD

**Issue by MajorTotem** [react-component/calendar#150]
I couldn't find this in the example / documentation.

You should be able to specify which day is the starting day of the week - for example Monday instead of Sunday.

**Comment by Valodya** [comment]
Hi, 

I get it via `GregorianCalendar`

```
const gregorianCalendar = new GregorianCalendar({
    firstDayOfWeek: 1
  })

...

 <Calendar value={ calendarDate } />

```
