### ISSUE TITLE
cannot set props to timepicker of calendar

### ISSUE THREAD

**Issue by freestyle21** [react-component/calendar#157]
In `AntDesign` I use:

```
<DatePicker showTime={{format: "HH:mm"}} />
```
it works on version `1.0.0`, But fail in version `2.0.0-beta.10`

I find out the `calendar` cover my inputed props `showHour | showSecond ` in [L201](https://github.com/react-component/calendar/blob/master/src/Calendar.jsx#L201)

Is it ?

**Comment by afc163** [comment]
@benjycui

**Comment by freestyle21** [comment]
修改 [L201](https://github.com/react-component/calendar/blob/master/src/Calendar.jsx#L201) 为
```
const timePickerEle = timePicker && showTimePicker ? React.cloneElement(timePicker, Object.assign({},{
      showHour: true,
      showSecond: true,
      onChange: this.onDateInputChange,
      defaultOpenValue: value,
      value: selectedValue,
      disabledHours: noop,
      disabledMinutes: noop,
      disabledSeconds: noop,
      ...disabledTimeConfig,
    }, timePicker && timePicker.props)) : null;
```
就正常了。

麻烦看看是否正确?

**Comment by benjycui** [comment]
@freestyle21 PR 吧。

然后这儿不需要再判断 `timePicker` 是否存在了，因为前面已经保证了。

```js
timePicker && timePicker.props
```

**Comment by afc163** [comment]
@benjycui 回头样式可能还需要处理一下。
