### ISSUE TITLE
How to change language of month names.

### ISSUE THREAD

**Issue by figalex** [react-component/calendar#163]
I already created a custom locale file for Spanish, but that does not changes the language for the month name on the calendar.

**Comment by benjycui** [comment]
`rc-calendar` will read month names from `value`, so you should set moment's locale to Spanish.

You had better create a PR to submit your Spanish locale, for there is no locale for Spanish in `rc-calendar` now.

**Comment by nelhu** [comment]
> `rc-calendar` will read month names from `value`, so you should set moment's locale to Spanish.
> 
> You had better create a PR to submit your Spanish locale, for there is no locale for Spanish in `rc-calendar` now.

thanks, you saved me a couple of  hours
