### ISSUE TITLE
Add value for `Select.Option`'s

### ISSUE THREAD

**Issue by TryingToImprove** [react-component/calendar#168]
I use `FullCalendar`, which have a "soft" dependency on `rc-select` which I do not use in  my project.

It would be nice if there were a `value` prop passed down to `Select.Option` which the month index.

Correctly a workaround is to clone the elements;

``` jsx
const Selector = ({ children, onChange, value }) => (
  <select defaultValue={value} onChange={(e) => onChange(e.target.value) }>
    {React.Children.map(children, (child, i) => React.cloneElement(child, { value: i }))}
  </select>
);
Selector.Option = ({ children, value }) => (<option value={typeof (children) === 'number' ? children : value}>{children}</option>);
```

Should I make a pull request for this?

**Comment by benjycui** [comment]
Sorry, what's your use case.

**Comment by TryingToImprove** [comment]
@benjycui Sorry, I can't remember what the use case was, and it seems like I found a workaround, so it can just be closed..
