### ISSUE TITLE
Get visible dates from DateTable

### ISSUE THREAD

**Issue by TryingToImprove** [react-component/calendar#169]
I currently making a calendar page, where I need to fetch data for the date visible in the calendar, therefor it would be awesome if the calendar provided a way to get the visible calendar.

I think that a utility class would be a great help

Current workaround (copied code from `DateTBody.jsx`

``` js
const getDates = (value) => {
  const dateTable = [];
  const month1 = value.clone();
  month1.date(1);
  const day = month1.day();
  const lastMonthDiffDay = (day + 7 - value.localeData().firstDayOfWeek()) % 7;
  // calculate last month
  const lastMonth1 = month1.clone();
  lastMonth1.add(0 - lastMonthDiffDay, 'days');
  let passed = 0;
  for (let iIndex = 0; iIndex < 6; iIndex++) {
    for (let jIndex = 0; jIndex < 7; jIndex++) {
      let current = lastMonth1;
      if (passed) {
        current = current.clone();
        current.add(passed, 'days');
      }
      dateTable.push(current);
      passed++;
    }
  }

  return dateTable;
}
```

I think that it would be a good idea to export that section of code into it's own module.  https://github.com/react-component/calendar/blob/master/src/date/DateTBody.jsx#L70

**Comment by twig** [comment]
I was looking for this functionality as well. At the moment it's a hackjob and I'm not proud to be using it but it does the job.

Surprised this wasn't available via `onChange()` or something

**Comment by twig** [comment]
For those looking for a function that just gives you the first and last dates, I've removed the loop which should save some processing time.

    // https://github.com/react-component/calendar/issues/169
    // - Added DateConstants
    // - Skip the loops
    getVisibleDates = (value) => {
      const DateConstants = {
        DATE_ROW_COUNT: 6,
        DATE_COL_COUNT: 7,
      };
  
      const dateTable = [];
      const month1 = value.clone();
      month1.date(1);
      const day = month1.day();
      const lastMonthDiffDay = (day + 7 - value.localeData().firstDayOfWeek()) % 7;
      // calculate last month
      const lastMonth1 = month1.clone();
      lastMonth1.add(0 - lastMonthDiffDay, 'days');
      let passed = 0;
  
      // First day
      dateTable.push(lastMonth1.clone());
      // Last day
      dateTable.push(
        lastMonth1.clone()
          .add(
            (DateConstants.DATE_ROW_COUNT * DateConstants.DATE_COL_COUNT) - 1,
            'days'
          )
      );
  
      return dateTable;
    }

**Comment by benjycui** [comment]
Actually, it's easy enough to get visible dates on your own, thank you for your advice.

**Comment by twig** [comment]
Is there an easier way than the way I mentioned?
