### ISSUE TITLE
Can't remove value from calendar's input

### ISSUE THREAD

**Issue by JulyV** [react-component/calendar#173]
Hi,

It looks like the onChange doesn't fire when I remove value from calendar's input. What could be the root cause?

**Comment by jaredmahan** [comment]
You could simply hide the input using css.
`.rc-calendar-input-wrap{
    display: none;
}`

**Comment by benjycui** [comment]
@JulyV please provide an re-producible online demo.

**Comment by benjycui** [comment]
Close for no response, and the official demo works fine.
