### ISSUE TITLE
两个 DatePicker 获取属性的问题

### ISSUE THREAD

**Issue by LeezQ** [react-component/calendar#18]
![image](https://cloud.githubusercontent.com/assets/972813/6820919/3997e8ce-d30e-11e4-9b95-3ee049538370.png)
我现在有两个 `<DatePicker />` 的组件，我现在想在 handleDateChange 方法里获取到 DatePicker 的 name 属性，有什么好的方法获取么？我现在比较龊的用了 `this.handleDateChange.bind(this, 'startTime', value)` 。。

**Comment by yiminghe** [comment]
是这样的

**Comment by LeezQ** [comment]
另外请教承玉大神，还有一点难理解的是，调用 this.handleDateChange 的时候，传入的一个参数值 value 是个 GregorianCalendar ，不应该是 event 么。。

**Comment by yiminghe** [comment]
自己写组件没法传 e 的，react 没有自定义事件机制
