### ISSUE TITLE
imported node_modules not compatible with ie8

### ISSUE THREAD

**Issue by jamaica474** [react-component/calendar#182]
My bundle contains `_interopRequireDefault` method with unescaped "default" property, which makes it incompatible with ie8.
From the bundle:
`
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
`

This piece of code is included with `node_modules/babel-runtime/helpers/possibleConstructorReturn.js` file. I have at least three unquoted "default: " in final bundle. This is how I use the calendar:
`
import React from 'react';
import moment from 'moment';
import 'rc-calendar/assets/index.css';
import Calendar from 'rc-calendar';
import locale from 'rc-calendar/lib/locale/en_US';
import DatePicker from 'rc-calendar/lib/Picker';

const calendarOptions = {
  defaultValue: moment(),
  locale,
  showDateInput: false,
};

const datePickerOptions = {
  animation: 'slide-up',
  calendar: <Calendar {...calendarOptions} />,
  align: {
    points: ['tl', 'bl'],
  },
};

const getValueFromEvent = (e) => (e) ? e.format('YYYY/MM/DD') : '';

const Data = (props) => (
  <DatePicker
    {...datePickerOptions}
    onChange={e => props.onChange(getValueFromEvent(e))}
  >
    {
      () => (
        <div className="input-group" >
          <input {...props} style={{ zIndex: 0 }} />
          <span className="input-group-addon">
            <i className="glyphicon glyphicon-calendar" />
          </span>
        </div>
      )
    }
  </DatePicker>
);

export default Data;
`

**Comment by benjycui** [comment]
We are not going to support IE8, for React and it's community had drop IE8.

**Comment by rubyless** [comment]
@benjycui 请问哪个版本是支持ie8的?

**Comment by benjycui** [comment]
@rubyless try 5.x
