### ISSUE TITLE
One calendar for date range select

### ISSUE THREAD

**Issue by neekey** [react-component/calendar#188]
Hi, can we have just one calendar for date range select, just like what Airbnb have already done: http://airbnb.io/react-dates/?selectedKind=DateRangePicker&selectedStory=single%20month&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel

this will be easier to integrate with mobile.

**Comment by benjycui** [comment]
Try [`rmc-date-picker`](http://react-component.github.io/m-date-picker/), if your target platform is mobile.

**Comment by devsli** [comment]
I find it easier to extend the `RangeCalendar` class and override the `render()` method. Rough example: https://gist.github.com/devsli/6bd30b522bdca4055a51adac8e55b5d3
