### ISSUE TITLE
Calendar: Can't disable today

### ISSUE THREAD

**Issue by CharlieScarver** [react-component/calendar#193]
I'm using rc-calendar and it's datepicker along with gregorian-calendar-format:

     import DateTimeFormat from 'gregorian-calendar-format';
     import RcCalendar from 'rc-calendar';
     import DatePicker from 'rc-calendar/lib/Picker';

I have a disabledDate function to disable some dates. Today should be disabled but when you open the picker[ today is marked as **selected**](http://puu.sh/t3uUj/4992d5817e.png) and **you can still select it**. If you pick another date and the blue marker moves, then [you can see that today is disabled and gray](http://puu.sh/t3uUZ/e3c219d2fb.png). After selecting another day you can no longer select today.

I tried giving **defaultValue** and **selectedValue** of **undefined** both to the picker and the calendar but no effect. 
Any help is appreciated.

**Comment by hchoriq** [comment]
You should include a copy of your function.

**Comment by benjycui** [comment]
`antd`'s DatePicker is a wrapper of `rc-calendar`, and it works fine when disabled today, see [demo](https://ant.design/components/date-picker/#components-date-picker-demo-disabled-date)

**Comment by benjycui** [comment]
Try to upgrade your `rc-calendar` to latest version, and if you still meet this problem, please provide a re-producible online demo, thanks.

**Comment by CharlieScarver** [comment]
I did a clean test with the latest version and can no longer reproduce the issue.
Thank you.
