### ISSUE TITLE
custom date cell render for regular calendar

### ISSUE THREAD

**Issue by chqy24** [react-component/calendar#195]
I noticed that FullCalendar has a prop of dateCellContentRender which support custom content render, can we do the same thing to a regular calendar?
Since I want add some event info into date cell.

**Comment by benjycui** [comment]
Try [`Calendar[dateRender]`](https://github.com/react-component/calendar/blob/b5e45c370c83976e1f258c49fe23b509081194af/src/Calendar.jsx#L256)

**Comment by benjycui** [comment]
If it works, please close this issue, thanks.
