### ISSUE TITLE
How Disable all past days ? 

### ISSUE THREAD

**Issue by alirezavalizade** [react-component/calendar#198]
i use [this](http://react-component.github.io/calendar/examples/start-end.html) example and want disable all past dates.

**Comment by idclev31** [comment]
yeah, it will be cool, if i can disable dates before selected

**Comment by fmaceachen-glb** [comment]
You can do this:

`disabledDate(current) {
    const date = moment();

    if (!current) {
      // allow empty select
      return false;
    }
    date.hour(0);
    date.minute(0);
    date.second(0);

    return current.isBefore(date);
  }`

`<Calendar
      .......
      disabledDate={this.disabledDate.bind(this)}

.........
    />`

**Comment by paranoidjk** [comment]
```md
disabledDate	Function(current:moment):Boolean		whether to disable select of current date
```
you can check this demo at here
 http://react-component.github.io/calendar/examples/antd-calendar.html

**Comment by paranoidjk** [comment]
going to close this, if you still have any problem, feel free to open a issue :)
