### ISSUE TITLE
defaultSelectedValue have no effect in RangeCalendar 

### ISSUE THREAD

**Issue by AlingChen** [react-component/calendar#199]
![image](https://cloud.githubusercontent.com/assets/11454349/21630151/8fd493c0-d269-11e6-9e90-bb64e5d12ffd.png)

![image](https://cloud.githubusercontent.com/assets/11454349/21630139/6050a152-d269-11e6-8191-dc5cbd310002.png)

**Comment by AlingChen** [comment]
Is there anyone have this issue? have any suggestion to resolve it? thanks

**Comment by sabarasaba** [comment]
@AlingChen hey im having the same problem now, were you able to solve it ?
