### ISSUE TITLE
React throws TypeError when clicking on Datepicker

### ISSUE THREAD

**Issue by minqi** [react-component/calendar#20]
I've nested the Datepicker component in a parent component. When clicking the datepicker, React throws this error:

Uncaught TypeError: Cannot read property 'firstChild' of undefined

I figured maybe I was incorrectly setting up my component, so I replaced my component with the component defined in the first example for rc-calendar, but found the issue still persisted. Clicking on Datepicker still throws this same error.
http://react-component.github.io/calendar/build/examples/ant-design-picker.html

The discussion on StackOverflow suggests that this error is caused by having 2 mismatched versions of React inside of a nested node-modules directory. However, this does not appear to be the case with the rc-calendar module.

**Comment by yiminghe** [comment]
better make react external and load react.js into head

http://webpack.github.io/docs/library-and-externals.html#applications-and-externals
