### ISSUE TITLE
How do you clear an existing selection ?

### ISSUE THREAD

**Issue by heswell** [react-component/calendar#204]
I have a calendar which I popup on demand. I want to clear the previous selection each time I re-display the calendar. Although I set selectedValue to null, which correctly sets the internal state, the previously selected day is still selected. What's the correct way to remove it ?

**Comment by benjycui** [comment]
I read source code, and it' should work. 

Try the latest version, if you still meet this issue, please provide a re-producible online demo, thanks.

**Comment by benjycui** [comment]
Close for no response.
