### ISSUE TITLE
Calendar body title format

### ISSUE THREAD

**Issue by vlkous** [react-component/calendar#211]
Hi,

is any problem use date format from calendar locale property?

Now I use DD.MM.YYYY format but on title I see YYY-MM-DD

File:
https://github.com/react-component/calendar/blob/master/src/date/DateTBody.jsx#L208

THX

**Comment by benjycui** [comment]
Please provide a re-producible online demo, thanks.

**Comment by benjycui** [comment]
Duplicated: https://github.com/react-component/calendar/issues/222
