### ISSUE TITLE
打开组件当展示月所有日期均禁用置灰状态时，确认按钮始终置灰不可点击

### ISSUE THREAD

**Issue by RK-WJW** [react-component/calendar#216]
如题，OK确认按钮始终置灰不可点击，即使切换了展示月份后存在可选日期，按钮状态依然是置灰的不可用。 示例效果如下图：
![image](https://cloud.githubusercontent.com/assets/6636353/23114332/613cf5c2-f779-11e6-9f11-6779bc949bb7.png)

![image](https://cloud.githubusercontent.com/assets/6636353/23114320/4c6312e4-f779-11e6-87f5-964f098cf139.png)

**Comment by benjycui** [comment]
Please provide a re-producible online demo

**Comment by RK-WJW** [comment]
已解决
