### ISSUE TITLE
Apply style/class to workdays?

### ISSUE THREAD

**Issue by dmitriyK1** [react-component/calendar#218]
Hi!
Is there any way to apply some custom styles to workdays (for rc-calendar default component)?
Thanks in advance.

**Comment by benjycui** [comment]
How about `td:nth-child(n)`?

**Comment by benjycui** [comment]
It's simple enough.

And you can event tell Monday Tuesday and so on.

**Comment by dmitriyK1** [comment]
Thanks!
Unfortunately I need to style days of the current week only
Any way to add some class name to current week <tr> ?
 
![image](https://cloud.githubusercontent.com/assets/3366893/23207618/97a3f5de-f8fa-11e6-99a2-18de4f085c00.png)

**Comment by benjycui** [comment]
It seems that you need to PR to add class name to current week

![image](https://cloud.githubusercontent.com/assets/3580607/23207987/41e57e4a-f92e-11e6-8a5a-8f489c284fd6.png)

**Comment by dmitriyK1** [comment]
Thanks, I will create PR soon then!
