### ISSUE TITLE
datepicker 的 focus 状态交互问题

### ISSUE THREAD

**Issue by afc163** [react-component/calendar#22]
地址：http://react-component.github.io/calendar/build/examples/ant-design-picker.html

浏览器：Firefox

操作步骤：

1. 点击输入框
   - 预期：展开浮层，输入框为 focus 状态
   - 实际：展开浮层，输入框并非 focus 状态
2. 再次点击输入框
   - 预期：浮层不动，输入框保持 focus 状态
   - 实际：收起浮层，输入框为 focus 状态

---

在 Chrome 下始终无法进入 focus 状态。

**Comment by yiminghe** [comment]
是这么设计的， input focus 弹出 calendar ，calendar 接收节点响应键盘事件，有更好建议？

**Comment by afc163** [comment]
和火烧云的交互一样就不错：http://si.alipay.im/jiuzhou/flaming-cloud-components/#/components/datepicker

**Comment by yiminghe** [comment]
下周见面聊

**Comment by afc163** [comment]
比如金融云的 input 样式有 focus 的效果，这样的话就丢掉了。代码还要特殊处理。

**Comment by yiminghe** [comment]
通过 rc-calendar-picker-open rc-calendar-picker-input 样式来控制吧
