### ISSUE TITLE
Change day cell title date string format?

### ISSUE THREAD

**Issue by zefj** [react-component/calendar#222]
in _src/util/index.js_

    export function getTitleString(value) {
        return `${value.year()}-${value.month() + 1}-${value.date()}`;
    }

This function is used to build a string that later gets used as an element's (day cell) title property. As you can see it is hardcoded, which results in tooltips with dates in incorrect and strangely-looking format, which [according to this](https://en.wikipedia.org/wiki/Date_format_by_country) is used literally nowhere. Would it be possible to use the format passed in props?

**Comment by benjycui** [comment]
Yep, what is your advice to improve this?

**Comment by zefj** [comment]
Maybe use the format passed to the component by the `format` prop?

**Comment by benjycui** [comment]
Yep, I had thought about that, but it's weirdo. Because `format` will be `YYYY-MM-DD HH:mm:ss`, and you will not want to show `HH:mm:ss` in day cell title.

**Comment by zefj** [comment]
How about splitting it into two props then? Eg. `dateFormat` and `dateTimeFormat`?

**Comment by benjycui** [comment]
Nope, we just follow moment's format.

**Comment by benjycui** [comment]
Keep it simple. Just use en-US's format in [your link](https://en.wikipedia.org/wiki/Date_format_by_country)

And PR is welcomed.

**Comment by zefj** [comment]
I'll work out a PR soon, I'll try to just use moment's localized format

**Comment by zefj** [comment]
Created a PR with fix, see: https://github.com/react-component/calendar/pull/268

**Comment by benjycui** [comment]
`rm -rf node_modules && npm i`
