### ISSUE TITLE
Hover presets date to highlight the range

### ISSUE THREAD

**Issue by afc163** [react-component/calendar#223]
<img width="304" alt="dingtalk20170306225809" src="https://cloud.githubusercontent.com/assets/507615/23615143/6482b350-02c0-11e7-8dcf-a84d698134de.png">

**Comment by benjycui** [comment]
rc-calendar 把 hoverValue 暴露为受控属性 https://github.com/react-component/calendar/pull/261

剩下交互优化需要在 antd 里面做。
