### ISSUE TITLE
month calendar 有被禁用的日期后，仍然可以通过切换年份，选择到被禁用的月份上。

### ISSUE THREAD

**Issue by eternalsky** [react-component/calendar#234]
http://react-component.github.io/calendar/examples/antd-month-calendar.html

官方提供的 demo 就可以复现。

**Comment by benjycui** [comment]
除了 MonthCalendar，Calendar & RangeCalendar 也有问题。

**Comment by eternalsky** [comment]
@benjycui 这个问题最近会跟进修复吗~

**Comment by benjycui** [comment]
尽量这周修复。

**Comment by benjycui** [comment]
![image](https://cloud.githubusercontent.com/assets/3580607/26046769/2189ef42-3983-11e7-9073-6138a65bc288.png)

看了下代码，其实我不是很确定 MonthCalendar 这个算不算 bug。

ping @yiminghe

**Comment by yiminghe** [comment]
不算 bug，onChange 是导航到的日期

**Comment by benjycui** [comment]
@eternalsky 所以 onSelect 才是选中，onChange 只是面板切换。。

这个我有时也很晕。
