### ISSUE TITLE
Add Events To Calendar

### ISSUE THREAD

**Issue by gate3** [react-component/calendar#236]
Hi, Wonderful work here. I want to add some events to the FullCalendar, but i don't know how to do that.  What i have done so far is create an event for the dateCellContentRender function and i logged it's return value which is a moment object, this way no date is rendered. But how do i make the dates show my events, please help

**Comment by benjycui** [comment]
> I want to add some events to the FullCalendar

More details?

**Comment by gate3** [comment]
I would like to add more events based on specific dates to the full calendar view. I want to be able to add elements that will carry the event name and once clicked can show maybe a dialog with further details.

**Comment by benjycui** [comment]
Pseudo code:

```jsx
dateCellContentRender={(date) => {
  return <div onClick={() => this.handleClick('eventName')}>...</div>
}
```
