### ISSUE TITLE
Week picker : Rendering start date and end date of the selected to the input field. 

### ISSUE THREAD

**Issue by likhita-palavali** [react-component/calendar#239]
I am using rc-calendar@7.8.0. (Week picker). 

http://react-component.github.io/calendar/examples/week.html

Can u please help me in retrieving start date  and end date of selected week and display same in the input field. 

I am trying to display the start date of the week and end date of the week in the following format : 
const format = "YYYY-MM-DD" to "YYYY-MM-DD".  
(Example : 2017-04-10 to  2017-04-16).

<img width="253" alt="screen shot 2017-04-03 at 10 27 33 pm" src="https://cloud.githubusercontent.com/assets/17817231/24669287/b5dd7afe-191e-11e7-87cf-645fd673a340.png">

Currently in the week picker it is shown as the following format 
const format = "YYYY-Wo";

<img width="261" alt="screen shot 2017-04-03 at 10 20 32 pm" src="https://cloud.githubusercontent.com/assets/17817231/24669221/746dd9a6-191e-11e7-937c-2d10ec88c711.png">

I am stuck in this place. 
Help would be greatly appreciated. 

Thank you in advance,
Likhita Palavali.

**Comment by benjycui** [comment]
You can calculate the start date and end date of any week [here](https://github.com/react-component/calendar/blob/baf968f2314043816e188265f345a9e1f997b17d/examples/week.js#L142-L158) with [moment's operator](http://momentjs.com/docs/), then format as you want.
