### ISSUE TITLE
浮层应提供默认 z-index

### ISSUE THREAD

**Issue by afc163** [react-component/calendar#24]
![](https://t.alipayobjects.com/images/T1GTFfXfdvXXXXXXXX.png)

**Comment by yiminghe** [comment]
ok，现在弹层是渲染到插入点，将提供选项，渲染到外层

**Comment by yiminghe** [comment]
moved to 26

**Comment by yiminghe** [comment]
http://react-component.github.io/calendar/build/examples/renderCalendarToBody.html
