### ISSUE TITLE
DisabledDate fires when selecting range

### ISSUE THREAD

**Issue by manutorre** [react-component/calendar#244]
Hi, I'm using the rangeCalendar and I'm stuck with this:
I have an array of dates that must be disabled in my calendar. Sometimes they are 2 or 3 and sometimes they are 10. 
I understand that with disabledDate every date cell evaluates the function and if It returns true, then It disables. 
However, I found a problem: when I select the first date of the range calendar, and move the mouse a little bit hovering over different days of the months, the disabledDate function fires all the time and there is a big impact on the UI. It works very slow. In the downloadable example this happens too. I didn't realize at the first time because the disabledDate function wasn't very demanding. But just with printing anything inside there, you will notice that It starts to get slow.
Hope someone could give me a hand with this !
Thanks!!

**Comment by benjycui** [comment]
Yep, maybe you can memoize your `disabledDate`.

rc-calendar must call `disabledDate` when it re-render, for `disabledDate` is a function, and rc-calendar don't know whether the return value of `disabledDate` will change while re-rendering.
