### ISSUE TITLE
How to stop event propagation in RangeCalendar?

### ISSUE THREAD

**Issue by namini67** [react-component/calendar#246]
We are using the Picker and RangeCalendar component within a home made component which collapses the UI when it is clicked outside of the panel (similar to a modal).
Clicking the RangeCalendar to select a date causes the panel it is rendered in to collapse. 
Is there a way to pass in a stopPropagation to the RangeCalendar component? 

Also, we noticed that the rendered Calendar component is not within the parent component, but is instead next to it. This might be the cause of our problem? Not to mention, onChange and onSelect in the RangeCalendar takes a Moment object in its passed in function, and not an event. 

![screen shot 2017-04-11 at 4 14 38 pm](https://cloud.githubusercontent.com/assets/4326384/24934715/1facfe4c-1ed2-11e7-9f93-e1cab773aaac.png)

**Comment by benjycui** [comment]
Try `getCalendarContainer` or  google `e.nativeevent.stopimmediatepropagation`
