### ISSUE TITLE
disabledMinutes is ignored in Range Calendar

### ISSUE THREAD

**Issue by ngort01** [react-component/calendar#249]
Hi everyone,

so I'm using the range calendar and I'm passing in a disabledMinutes function.
It works fine if start and end days are not the same but if they are the same it is ignored for the second time panel. 
You can reproduce it in the examples http://react-component.github.io/calendar/examples/antd-range-calendar.html.
Choose the same day for start and end and take a look at e.g. the seconds in the right time panel.

Is this a bug or working as intended?

Kind regads
Niko

**Comment by benjycui** [comment]
I think it works fine. So, what is your expected behavior?

**Comment by ngort01** [comment]
I expected that if I pass in a disabledMinutes function those minutes are disbaled in both time picker panels but they are not if start and end day are the same:

Here it works as expected (different start and end days)
![1](https://cloud.githubusercontent.com/assets/3532768/25266248/d42ffce8-2670-11e7-9bc2-5ca8599d9256.png)

Here disabled minutes are ignored in the right time picker.
![2](https://cloud.githubusercontent.com/assets/3532768/25266296/fa089a38-2670-11e7-8a64-51f9e43119b2.png)

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/jBbdLZ?editors=0010

**Comment by benjycui** [comment]
Close for no response.
