### ISSUE TITLE
duplicate datepicker in same range 

### ISSUE THREAD

**Issue by fanliming** [react-component/calendar#254]
expect:

![image](https://cloud.githubusercontent.com/assets/3654543/25418250/22c13c9c-2a85-11e7-9ca0-ee38c8f6fb31.png)

now:

![2017-04-26_133143](https://cloud.githubusercontent.com/assets/3654543/25418226/03111534-2a85-11e7-822b-ab804609c341.png)

**Comment by benjycui** [comment]
It works fine http://react-component.github.io/calendar/examples/antd-range-calendar.html

Try `rm -rf node_modules && npm i`

**Comment by fanliming** [comment]
选同一个月的日期之后 再重新打开，就是下面的样子。

![image](https://cloud.githubusercontent.com/assets/3654543/25426664/d4e28366-2aaa-11e7-933b-14fb081dda91.png)

**Comment by benjycui** [comment]
fixed, and we can simplify antd.RangePicker's code.
