### ISSUE TITLE
Option to display week per week

### ISSUE THREAD

**Issue by baptistedonaux** [react-component/calendar#263]
New option such as year and month display.

I can't find this option. It's scheduled ?

**Comment by benjycui** [comment]
I don't understand, do you mean this? http://react-component.github.io/calendar/examples/week.html

**Comment by baptistedonaux** [comment]
I think at an option similary at **react-big-calendar** when type selected is `week`.

http://intljusticemission.github.io/react-big-calendar/examples/index.html

**Comment by benjycui** [comment]
> I think at an option similary at react-big-calendar when type selected is week.

If you mean this, nope. Almost re-implement this calendar.
