### ISSUE TITLE
Help request

### ISSUE THREAD

**Issue by mentrie** [react-component/calendar#267]
I want to know if there's a way of embedding data for days in a month. Basically, I want to fetch data from an API and render a time frame for each of the days.

**Comment by paranoidjk** [comment]
You should give some pseudocode at least.

**Comment by mentrie** [comment]
![calender-question](https://cloud.githubusercontent.com/assets/15085641/26734109/d2c3bc7c-47b4-11e7-9733-4e2a83080f6b.png)

**Comment by benjycui** [comment]
> I want to know if there's a way of embedding data for days in a month. Basically, I want to fetch data from an API and render a time frame for each of the days.

I try to understand... I think you can use map:

```jsx
{
  ''2017-06-20': ...
}
```

**Comment by benjycui** [comment]
Close for no response.
