### ISSUE TITLE
Locale files without country 

### ISSUE THREAD

**Issue by kishorevarma** [react-component/calendar#270]
Hi,

1) Is there any chance that we can add locale files without country
for example at present for fr we have two fiels `fr_FR.js`, and `fr_BE.js`,it would be good if we have default `fr.js`

2) Can we have a index.js file that exports all the locale files. so that we can import all locale data, and select locales dynamically.

```
import alLocales from 'rc-calendar/lib/locale';

const locale = 'en'
....
render() {
  return (
     <Calendar
         locale={alLocales[locale]}
     />
  )
}

```

**Comment by benjycui** [comment]
> Is there any chance that we can add locale files without country
> for example at present for fr we have two fiels fr_FR.js, and fr_BE.js,it would be good if we have default fr.js

I don't understand, could you provide more information? Just add a locale file? Or change the behavior of rc-calendar?

**Comment by benjycui** [comment]
> Can we have a index.js file that exports all the locale files. so that we can import all locale data, and select locales dynamically.

It's not recommended, you can try to use webpack resolve.context or something like that.

**Comment by kishorevarma** [comment]
thanks @benjycui 

> It's not recommended, you can try to use webpack resolve.context or something like that.

ContextReplacementPlugin can be used if you know the locale at the compile time,I don't think we can use that if you get locale at run time (example user selecting locale from dropdown)

> I don't understand, could you provide more information? Just add a locale file? Or change the behavior of rc-calendar?

Sorry I could't explained well, for example you have a drop down to select locale from a list of locales(fr, en, de) and assume user selected `fr` now I need to load that specific locale(`fr`) and pass it to `Calendar` component. 

At present its not possible load `fr.js` because we have `fr_FR.js` and `fr_BE.js` no `fr.js` .

In both of the scenarios list of locales are dynamic(assume added by some admin).

Please let me know if you need more info or if you think this is not common use case please ignore

**Comment by benjycui** [comment]
1. webpack `require.context` works as fine as we add a new entry file for all the locale files.
1. Just map `fr` to `fr_FR` or `fr_BE`, don't make things too complicated.
