### ISSUE TITLE
Dependencies still using createClass and React.PropTypes

### ISSUE THREAD

**Issue by zackify** [react-component/calendar#273]
Looks like the trigger is still on an old version
![image](https://user-images.githubusercontent.com/449136/27290234-9b2f5cfc-54da-11e7-86db-f5f7c4def0a4.png)

![image](https://user-images.githubusercontent.com/449136/27290300-c73887ba-54da-11e7-9242-a9786600b027.png)

**Comment by paranoidjk** [comment]
https://github.com/react-component/trigger/pull/51

nope，trigger already fixed this problem，please try to upgrade your deps.

**Comment by zackify** [comment]
There's definitely a problem with the 8.4 releases. Installing 8.3 works fine. Using 8.4 without installing rc-util on my own causes this: 
![image](https://user-images.githubusercontent.com/449136/27297500-0f47dc1e-54f3-11e7-8291-aa5df20396ef.png)

**Comment by paranoidjk** [comment]
you need to upgrade your deps.

@benjycui should change pkg.deps.rc-util to ^4.0.4
