### ISSUE TITLE
Design not consistent when value is set

### ISSUE THREAD

**Issue by hackhat** [react-component/calendar#274]
When `value` is set on the first render looks like this:
![image](https://user-images.githubusercontent.com/11173732/27486815-b21b02ca-5829-11e7-8d4c-37795375a043.png)
After I click on the same date looks like this:
![image](https://user-images.githubusercontent.com/11173732/27486840-ca82c974-5829-11e7-852f-95242aa6dbf9.png)
Why is different when the value is the same?

**Comment by benjycui** [comment]
`value` and `selectedValue` are different. Please consult the documentation.
