### ISSUE TITLE
Missing option to start from time selection

### ISSUE THREAD

**Issue by damian-codilime** [react-component/calendar#275]
I could be missing something, but could not find an option to start date-time picker from `time` selection.
I have an use case when user wants to select `time` range, but for periods that span trough the midnight, also the `date`.
Ex.
By default i wan't to select time range: `04.07.2017 11:00 - 04.07.2017 11:05`
But i also need to support this case: `03.07.2017 23:59 - 04.07.2017 00:05`

Therefore i would like to start the picker in `time` selection and have ability to go to `date` picker, which is not achievable for now.

**Comment by benjycui** [comment]
How about this? https://github.com/ant-design/ant-design/issues/5190

**Comment by damian-codilime** [comment]
Would be nice.

**Comment by benjycui** [comment]
Trace: ant-design/ant-design#5190
