### ISSUE TITLE
Range calendar: limit end date when select start date

### ISSUE THREAD

**Issue by phuongtran809** [react-component/calendar#276]
Hello,
I would like to make limit date selection. 
When I choose a start date, I want to limit end date <= 30 days. How can I do it.
Your help will be much appreciated.
Thanks

**Comment by benjycui** [comment]
You can control this with `value` `selectedValue` `hoverValue`

**Comment by phuongtran809** [comment]
Hi,

I dont see hoverValue option

**Comment by paranoidjk** [comment]
@phuongtran809 I have updated doc. see https://github.com/react-component/calendar#rc-calendarlibrangecalendar-props

ref https://github.com/react-component/calendar/pull/261

**Comment by phuongtran809** [comment]
Thanks for your answer @paranoidjk, I still dont know how to disable more than 10 days from startDate which I selected.
What I want to do:  I select startDate, I want user only can choose next 10 days, more than next 10 days will be disabled.

Your help will be much appreciated

**Comment by paranoidjk** [comment]
@phuongtran809 https://github.com/react-component/calendar/blob/master/examples/start-end-range.js#L43 I think you can use `hoverValue + onHoverChange` to make it under control.

**Comment by phuongtran809** [comment]
Thanks @paranoidjk, I did it.
This is my solution:

onChange(value) {
        this.setState({
            startDateSelected: value[0]
        });
    }
    disabledDate(value) {
        const { startDateSelected } = this.state;
        let startDate = startDateSelected;
        if (startDate !== null) {
            return value > moment(startDate + 9 * 24 * 3600 * 1000)
        }
    }

<RangeCalendar
                showWeekNumber={false}
                disabledDate={this.disabledDate}
                onChange={this.onChange}
            />
