### ISSUE TITLE
Calendar header formatting

### ISSUE THREAD

**Issue by dmitriyK1** [react-component/calendar#281]
Hi, I'd like to ask how can I configure header date format (month name format to be specific)?
Thanks in advance.

![](https://image.prntscr.com/image/UjgfwDc8TtGWwBlg3PK0Qg.png)

**Comment by benjycui** [comment]
Actually, you cannot configure it now.

**Comment by dmitriyK1** [comment]
Thanks, I used a patched moment instance to solve this for now, but this is a hacky solution
momentDate._locale.monthsShort = momentDate._locale.months;
