### ISSUE TITLE
How to catch event when I select start date in RangeCalendar

### ISSUE THREAD

**Issue by phuongtran809** [react-component/calendar#285]
Hello,
I would like to know how can I catch event when I select startDate
I select startDate, and print console.log startDate before I select endDate

Many thanks

**Comment by comeriven** [comment]
I also encountered this bug, maybe I need to clone it locally to modify it. If you have good advice, I will be very grateful.

**Comment by phuongtran809** [comment]
Hello @comeriven,

I found solution. Use _onChange_

**Comment by comeriven** [comment]
@phuongtran809 
hi , Are you using antd?  
Can you initiate a pull request, to antd to fix this problem for antd?
thanks

**Comment by comeriven** [comment]
@phuongtran809 
https://github.com/ant-design/ant-design/issues/6999 
this.
