### ISSUE TITLE
RangePicker 手动输入开始日期

### ISSUE THREAD

**Issue by comeriven** [react-component/calendar#286]
# 环境
Chrome 版本 60.0.3112.78（正式版本） （64 位）
visual studio code 版本 1.14.2  
node v6.11.0
npm v3.10.10  

# 源代码
![image](https://user-images.githubusercontent.com/19868056/28880690-6938b786-77d8-11e7-8a66-1709bf783b32.png)

# 问题
![image](https://user-images.githubusercontent.com/19868056/28880729-85f4499e-77d8-11e7-9982-76e7aecf3e09.png)
如图所示，按照‘yyyy-MM-dd’格式，在开始日期中输入一个日期，完成后开始日期的input自动清空。如下图。
![image](https://user-images.githubusercontent.com/19868056/28880802-adf8fe3a-77d8-11e7-87af-cd3e65a86228.png)

**Comment by benjycui** [comment]
ref: https://github.com/ant-design/ant-design/issues/6999

**Comment by paranoidjk** [comment]
![untitled](https://user-images.githubusercontent.com/7971415/28902016-ddc238d8-782e-11e7-9ad0-f81220143bdb.gif)

http://react-component.github.io/calendar/examples/start-end-range.html
