### ISSUE TITLE
How use api disabledDate for rangecalendar

### ISSUE THREAD

**Issue by VaskaDogana** [react-component/calendar#288]
```
<RangeCalendar onSelect = {this.select_value_calendar}
		       disabledDate = {what must be here??}
```
I need block all date from today and for all future, allowed data mast be only past  
what do you mean Function(current:GregorianCalendar):Boolean	??
Do  you can write example?

**Comment by benjycui** [comment]
See: http://react-component.github.io/calendar/examples/start-end-range.html

**Comment by VaskaDogana** [comment]
I looked for example, but I try disable period from parent component.
I do
`function disabledStartDate(endValue) {
			    if (!endValue) {
			      return false;
			    }
			    const startValue = moment().add(1, 'days');
			    if (!startValue) {
			      return false;
			    }
			    return endValue.diff(startValue, 'days') < 0;
			  }`
and then
`<RangeCalendar onSelect = {this.select_value_calendar}
			      disabledDate={disabledStartDate(moment().add(500, 'days'))}`
Have warning: Failed prop type: Invalid prop `disabledDate` of type `boolean` supplied to `RangeCalendar`, expected `function`.
And disabled date don't work.

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/jBbdLZ?editors=0010
