### ISSUE TITLE
"Error: Multiple anonymous defines."

### ISSUE THREAD

**Issue by wdlb** [react-component/calendar#289]
I'm using the rc-calendar (9.1.3) in a React application, using SystemJS as the module loader. When testing the app in the browser everything works fine. But when building the single .js and .css file, things go wrong: "Error: Multiple anonymous defines.", and it seems this error is caused by the "node_modules/rc-calendar/dist/rc-calendar.js" I'm importing. Does anybody has an idea how I could solve this, or give me some pointers on what exactly causes this error? Thanks a lot!

**Comment by benjycui** [comment]
I am not familiar with SystemJS, but if you can provide a re-producible repo, I can try to find issue.

**Comment by benjycui** [comment]
Close for no response.
