### ISSUE TITLE
disabled 情况下展示的日期不对齐

### ISSUE THREAD

**Issue by afc163** [react-component/calendar#29]
http://ant-design.github.io/components/datepicker/ 点击范围那个 input ，展现的日期样式不对齐。

![](https://t.alipayobjects.com/images/T1HU0fXlplXXXXXXXX.png)

**Comment by yiminghe** [comment]
weird  :weary:

**Comment by yiminghe** [comment]
改下样式就好了 https://github.com/react-component/calendar/commit/724d5ae7829e2602494aaca84703b330d47db550

**Comment by afc163** [comment]
rc-style 里改下？

**Comment by yiminghe** [comment]
https://github.com/ant-design/style/commit/926addc4ff81a15a5b82900928176e36a9bbc05a
