### ISSUE TITLE
点击日期控件报错，getContainerRenderMixin报错

### ISSUE THREAD

**Issue by zhongning7924** [react-component/calendar#290]
问题：
getContainerRenderMixin.js:41 Uncaught TypeError: getComponent is not a function
    at _renderComponent (getContainerRenderMixin.js:41)
    at Object.renderComponent (getContainerRenderMixin.js:64)
    at Object.componentDidUpdate (index.js:176)
    at CallbackQueue.notifyAll (CallbackQueue.js:65)
    at ReactReconcileTransaction.close (ReactReconcileTransaction.js:81)
    at ReactReconcileTransaction.closeAll (Transaction.js:202)
    at ReactReconcileTransaction.perform (Transaction.js:149)
    at ReactUpdatesFlushTransaction.perform (Transaction.js:136)
    at ReactUpdatesFlushTransaction.perform (ReactUpdates.js:86)
    at Object.flushBatchedUpdates (ReactUpdates.js:147)
原因：rc-calendar模块有依赖rc-util，使用node 7版本之后，rc-util模块于rc-calendar处于统一目录层级了，当rc-util模块放在rc-calendar/node_modules 里面的时候则可以正常使用，该问题如何解决？

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/jBbdLZ?editors=0010

**Comment by zhongning7924** [comment]
@benjycui  代码已经添加 一个最简单的日期输入框，
```js
 import Calendar from 'rc-calendar';
import DatePicker from 'rc-calendar/lib/Picker';

  <DatePicker
        animation="slide-up"
        disabled={false}
        calendar={calendar}
        onChange={this.handleDateChange.bind(this,'startDate')}
       >
       {
          ({ value }) => {
            return (

              <input className="form-control datetime"
                style={{ width: 250 }}
                disabled={false}
                className="form-control"
                value={this.state.startDate!==''? 
                moment(this.state.startDate).format('YYYY/MM/DD'):null}
                onChange={this.handleDateChange}
              />
            );
          }
        }
       </DatePicker> 
```

**Comment by benjycui** [comment]
？？？？？

可重现的在线 demo 和重现步骤，不要让人猜。

**Comment by zhongning7924** [comment]
@benjycui sorry 我第一个在原因里面有说明的，线上应该重现不了，rc-calendar模块有依赖rc-util，使用node 7版本之后，rc-util模块于rc-calendar处于同一目录层级了，当rc-util模块放在rc-calendar/node_modules 里面的时候则可以正常使用，你看看你本地的依赖关系，然后放上我这段代码看看 点击日期框直接抛出错误。

**Comment by afc163** [comment]
给出能重现的 repo。

**Comment by zhongning7924** [comment]
@afc163  刚写了个demo失落的发现没错误，[https://github.com/zhongning7924/demo](url)，
我自己项目里面rc-util有2处安装，一个在rc-calendar/node_modules/rc-util,一个在最外层与rc-calendar平级，这样就报错了。。。先关闭吧 麻烦各位了~

**Comment by benjycui** [comment]
@zhongning7924 可以尝试排查导致项目内安装了两个不同版本的 rc-util 的原因。

**Comment by zhongning7924** [comment]
@benjycui  可能是我之前引入rc-calendar与rc-time-picker的版本新旧不同导致里面引用的rc-util版本不同，原因可以确定是util版本不同引发的，我demo强制安装了一个rc-util 3x的版本，rc-calendar 引用的是4x的版本就会报错，[https://github.com/zhongning7924/demo](url)

**Comment by benjycui** [comment]
我 clone 你项目，删除这个依赖就正常了。

![image](https://user-images.githubusercontent.com/3580607/30054536-f39c35a6-925e-11e7-88fe-d8ecf7973b41.png)

**Comment by zhongning7924** [comment]
@benjycui o(╯□╰)o
