### ISSUE TITLE
adding week view for fullCalendar

### ISSUE THREAD

**Issue by kairi1227** [react-component/calendar#296]
hi, @benjycui 
I plan to add week view for fullCalendar.
so, I have achieved some functions in [my fork](https://github.com/kairi1227/calendar)

Please give me suggestions before PR.

**Comment by benjycui** [comment]
Ref: https://github.com/react-component/calendar/issues/263

**Comment by kairi1227** [comment]
@benjycui 
I have added a week view component in my fork.
[https://github.com/kairi1227/calendar/blob/master/src/week/WeekPanel.jsx](https://github.com/kairi1227/calendar/blob/master/src/week/WeekPanel.jsx)
And have added the week view to FullCalendar, result as follow:
![image](https://user-images.githubusercontent.com/4525647/30309327-658eeb96-97bd-11e7-89f5-579cc07a9d3c.png)
I think:
 1. The week view displays only on fullscreen FullCalendar .
 2. No implement event cell, provide a cell render function.
 3. Provide four params: isShowAllDay, timeFormat, weekCellHeaderRender,weekCellContentRender 

Then, I want to know what else I need to do before PR。

**Comment by benjycui** [comment]
No, don't integrate weekpanel into rc-calendar.

You can wrap rc-calendar and add weekpanel to it, thanks.
