### ISSUE TITLE
Passing of value prevents changing of month in calendar

### ISSUE THREAD

**Issue by zonzujiro** [react-component/calendar#297]
Hello!

I can't understand next behavior.

If I pass `value` to `Calendar`, I can't switch months. But if I pass `defaultValue` — it working, like it should be.

Not sure if this is related info, but I think it must be mentioned —  I need some custom logic for footer and inputs, so I wrapped your Calendar with my component.

Also, `onChange` listener fired in both cases — for `value` and for `defaultValue`.

Here example of code:
```
import DayCalendar from 'rc-calendar';

<div ref={elem => (this.datePicker = elem)} className="date-picker">
  <div className="calendar-wrapper">
       {isOpened &&
         <div className={classNames('calendar', calendarType)}>
         <DayCalendar
            className="flat-calendar"
            showDateInput={false}
            showToday={false}
            onSelect={this.onCalendarSelect}
            disabledDate={this.disabledDate}
            dateRender={this.renderDate}
            value={value}
            onChange={console.log}
           />
          <div className="footer">
               {/* .... */}
          </div>
       </div>}
   </div>
   <div className="date-picker-value-container">
      <div onClick={this.toggleVisibility} className="calendar-icon">
           {icon}
       </div>
       <input
         className="date-picker-value"
         value={inputValue}
         onChange={this.onInputChange}
         placeholder={dateFormat}
         onBlur={this.onInputBlur}
         onFocus={this.onInputFocus}
        />
    </div>
 </div>
```

**Comment by zonzujiro** [comment]
Update:

Not working either. 

`<Calendar showDateInput={false} showToday={false} value={fromMoment} />`

It looks like a bug for me, but this is so I will put the label.

**Comment by benjycui** [comment]
Think in React https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by zonzujiro** [comment]
I'm thinking and using controlled component, which passes value to your calendar.

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/jBbdLZ?editors=0010

**Comment by Dimon70007** [comment]
Hi guys. also have this behaviour. And it fixes when i use defaultValue instead value. It's strange, but with defaultValue it works fine.

**Comment by Dimon70007** [comment]
I think it occur because inner calendars state depends on value and can not toggle it when value comes from props. Although in example all works fine (it breaks my mind))))

**Comment by zonzujiro** [comment]
@Dimon70007 solved in same way :)
