### ISSUE TITLE
Setting showToday to false breaks view

### ISSUE THREAD

**Issue by yjzzcao** [react-component/calendar#299]
```
<Calendar
    value={ value }
    format="YYYY-MM-DD"
    showDateInput={ false }
    showToday={ false }
></Calendar>
```

![image](https://user-images.githubusercontent.com/2212428/30576967-e6d41746-9d3d-11e7-9964-783960dbf099.png)

**Comment by benjycui** [comment]
You can PR to fix it, thanks!

**Comment by costagolub** [comment]
@yjzzcao I can look at the issue and PR is you don't mind.

**Comment by benjycui** [comment]
@costagolub 👍
