### ISSUE TITLE
当前选中的高亮日期不准确

### ISSUE THREAD

**Issue by afc163** [react-component/calendar#30]
在进行月份和年份进行切换时，当前高亮（蓝底白字）的日期会跟随变化。

比如当前选中的是 6 月 1 日，面板切换到 5 月时，5 月 1 日也会高亮（正确的情况是不高亮）。

http://react-component.github.io/calendar/build/examples/ant-design-picker.html

**Comment by yiminghe** [comment]
这个是当前日子（不是当天）高亮，火烧云也这样啊，today 一般要有另外个样式 :

bootstrap 是绿框

http://react-component.github.io/calendar/build/examples/simple.html

**Comment by afc163** [comment]
和今天没关系。

高亮的应该是当前日期，不应该是当前“日”。

**Comment by afc163** [comment]
类似我选中了 6 月 4 日，月份切到 5 月，高亮的应该还是 6 月 4 日，而不是 5 月 4 日。

![](https://t.alipayobjects.com/images/T1xXXgXdXkXXXXXXXX.png)

**Comment by yiminghe** [comment]
这个先加个 today 的样式吧，高亮是还有方向盘导航的意思
