### ISSUE TITLE
RangeCalendar.js   selectedValue will be undefined

### ISSUE THREAD

**Issue by layne0625** [react-component/calendar#306]
The selectedValue of state will be undefined, I don't know the reason;  RangeCalendar's getStartValue and getEndValue function will bug;
I think 'selectedValue[0] && this.props.timePicker  ' will have some problem

**Comment by layne0625** [comment]
"selectedValue[0] && this.props.timePicker"  beacome "selectedValue && selectedValue[0] && this.props.timePicker" will be better;

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/jBbdLZ?editors=0010
