### ISSUE TITLE
rc-calendar/lib/RangeCalendar  设置 默认值失效 

### ISSUE THREAD

**Issue by panwenhua** [react-component/calendar#307]
<RangeCalendars
                        showToday={false}
                        showWeekNumber={true}
                        dateInputPlaceholder={['开始时间', '结束时间']}
                        showOk={true}
                        showClear={true}
                        format={'YYYY-MM-DD'}
                        onOk={this.submit}
                        defaultValue={[moment('2017-06-06', 'YYYY-MM-DD'), moment('2017-12-06', 'YYYY-MM-DD')]}
                    />

![image](https://user-images.githubusercontent.com/22313487/31484097-7fde737a-af61-11e7-8cb9-da44e29ae787.png)
defaultValue并没有设置上。

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/jBbdLZ?editors=0010

**Comment by panwenhua** [comment]
好久没看了，已经换了种实现方式 。谢谢
