### ISSUE TITLE
添加回车选中的快捷键

### ISSUE THREAD

**Issue by afc163** [react-component/calendar#31]

**Comment by yiminghe** [comment]
现在有的啊

**Comment by afc163** [comment]
对，是有 Timepicker 的没有。

**Comment by yiminghe** [comment]
http://react-component.github.io/calendar/build/examples/ant-design-picker.html  有的啊

看控制台

**Comment by afc163** [comment]
嗯，奇怪刚才是因为啥没有。。。先关了。

**Comment by afc163** [comment]
发现了，是 Timepicker 的输入框 focus 时和选择分秒的面板展开时，回车无法选中。

**Comment by yiminghe** [comment]
focus 不会弹出分秒的

是鼠标点击弹出分秒的面板后就只支持鼠标操作了
