### ISSUE TITLE
如何更改full-calendar固定行数

### ISSUE THREAD

**Issue by layne0625** [react-component/calendar#314]
当full-calendar按月份展示时， 可能出现最后一行全是下一个月的日期。 看了一下源代码， 日历表格固定设置成了6行 7列， 不知道是否可以通过参数修改？
![image](https://user-images.githubusercontent.com/24985105/32584096-c8c31a92-c531-11e7-9dcd-4be9329a2821.png)

**Comment by benjycui** [comment]
不能，高度可变的话，在切换月份时，会引发页面抖动的。
