### ISSUE TITLE
@3.8.0版本 showClear不能用了

### ISSUE THREAD

**Issue by fcm10101** [react-component/calendar#32]

**Comment by yiminghe** [comment]
sorry...

**Comment by fcm10101** [comment]
还有  我想问下  点击某一天 就会关闭日历  是由什么触发样式改变的的  感觉renderCalendarToBody.js与ant-design-picker.js没什么区别  为什么前面的点击后会关闭

**Comment by yiminghe** [comment]
有时分秒选择就不会自动关

**Comment by fcm10101** [comment]
能不能让input输入框的属性  固定加在input上   如果我在input外面放一个span的话  就会加到span上

**Comment by yiminghe** [comment]
span 加在 datepicker 外边
