### ISSUE TITLE
In antd-calendar example, text cursor jumps to beginning of input text field on entry

### ISSUE THREAD

**Issue by jtmoulia** [react-component/calendar#320]
Every time a character is entered in the example calendar text field, the cursor jumps to the beginning of the input text field. See the screen capture below:

![rc-calendar-caret-bug](https://user-images.githubusercontent.com/1057862/33295001-08723998-d388-11e7-919b-d0c9152715c3.gif)

I'm experiencing this issue with Chrome and Firefox 57.

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by jtmoulia** [comment]
I'm experiencing the issue with this repo's `antd-calendar` example: http://react-component.github.io/calendar/examples/antd-calendar.html

Happy to move the code into a codepen if that'd help.

**Comment by jtmoulia** [comment]
Closing in favor of #319 -- thanks!
