### ISSUE TITLE
Calendar Input Date 

### ISSUE THREAD

**Issue by doarrison** [react-component/calendar#324]
I seem to have a problem using the dateInput on the top of the calendar (the one enabled with showDateInput prop). It seems the cursor position on the input resets itself for each character I type causing the typing to go right to left. It's probably easier to know what I mean by trying it. For example if I try to type 2017-12-11 it will come out as 11-21-7102. I've also checked that this happens on the antd components example webpage so its not just my local environment. 

I'm guessing it has to do with the default onChange function inside the calendar component but I can't tell for certain. I don't think this problem existed with the old version of the component.

Regards.

**Comment by benjycui** [comment]
trace: https://github.com/react-component/calendar/pull/322
