### ISSUE TITLE
Can not change month or year from UI.

### ISSUE THREAD

**Issue by arshtepe** [react-component/calendar#330]
When i pass "value" props, it breaks month and year buttons.
```jsx
<Calendar showDateInput={false} showToday={true} value={dateValue}/>
```
The problem is that when I click for example "next month" button
https://github.com/react-component/calendar/blob/master/src/calendar/CalendarHeader.jsx#L204
it calls "goMonth" method
https://github.com/react-component/calendar/blob/master/src/calendar/CalendarHeader.jsx#L9
which, in turn, calls setValue
https://github.com/react-component/calendar/blob/master/src/mixin/CalendarMixin.js#L104
and inside setValue we have the following "if" clause which ignores value change if property "value" was passed. 
```js
if (!('value' in this.props)) {
      this.setState({
        value,
      });
    }
```

**Comment by yutingzhao1991** [comment]
When you use `value` prop, it means the component is a controlled components, so you should set value manually when onChange called.

Or, you can use `defaultValue` replace `value`.

**Comment by arshtepe** [comment]
@yutingzhao1991  But if i use defaultValue panel doesn`t change when defaultValue update.  For example i have input with date and next I change input value after state update and i have new date, but month panel stay same.

**Comment by afc163** [comment]
https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by arshtepe** [comment]
@afc163 Hi, I know it, but I don`t understand how it help in my case.

**Comment by arshtepe** [comment]
@yutingzhao1991 @afc163  My example https://jsfiddle.net/69z2wepo/97771/ you need change year in input. It is work but i can not switch between month.

**Comment by vaziliybober** [comment]
@afc163 @yutingzhao1991 several people have pointed out this issue, and you just keep referring them to react controlled components docs. Can you please pay attention and see that the value IS BEING SET MANUALLY when onChange happens. The VALUE is being updated correctly, but you can't switch between MONTHS and YEARS in the UI. Just see the example from the comment above.
