### ISSUE TITLE
可以把 import css 那一行放在readme 吗

### ISSUE THREAD

**Issue by cky-BryanChan** [react-component/calendar#332]
可以把 import css 那一行放在readme 吗？
import 'rc-calendar/assets/index.css'

我是在 example 里面才找到， 有些人（像我）可能不知道怎么去找

谢谢🙏

**Comment by afc163** [comment]
PR is welcome

**Comment by cky-BryanChan** [comment]
access denied when publishing  a branch

**Comment by afc163** [comment]
Try pull request
