### ISSUE TITLE
I want to get the value of the input box？

### ISSUE THREAD

**Issue by liuzhenbase** [react-component/calendar#336]
![image](https://user-images.githubusercontent.com/14008312/35203330-a37af8de-ff62-11e7-8f25-0b201d7678c3.png)

I am a novice.
I want to get the value of the input box？
But get the `Moment` object, rather than `20180117` format string.
My code

```
  onStartChange = (value) => {
        this.setState({
            startValue: value[0],
            startOpen: false,
            endOpen: true,
        })
    }
```

**Comment by yesmeck** [comment]
You can calling `format` on `value`, e.x `value.format('YYYYMMDD')`.

**Comment by liuzhenbase** [comment]
thanks🙏
