### ISSUE TITLE
Add a class of last-day on each last day of a month

### ISSUE THREAD

**Issue by ysyfff** [react-component/calendar#342]
The last day of the month is which day of the week is uncertain.
It's not realistic (as far as I know) to get the last day through css to style it.
So I hope to  add a last-day class to the last day via js.

Thanks!

**Comment by yesmeck** [comment]
Why do you want style it?

**Comment by ysyfff** [comment]
@yesmeck 

As the follow picture. I want to set the border of it when it was in range.
![image](https://user-images.githubusercontent.com/2571290/35503156-450e03e6-051a-11e8-8c1b-94020ab50cdc.png)

**Comment by yesmeck** [comment]
Welcome PR

**Comment by ysyfff** [comment]
I give an idea, hope you realize it. Because I am lazy, Ahhhhh

**Comment by ysyfff** [comment]
@yesmeck already PR
