### ISSUE TITLE
Setting showToday to false breaks render 

### ISSUE THREAD

**Issue by RalphSleigh** [react-component/calendar#36]
So rendering:

    <Calendar showToday={false} />

Gives:

    Uncaught Error: Invariant Violation: CalendarFooter.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.

Appears in the CalendarFooter.render() method the returned footerEl element is created inside:

    if (props.showToday || props.showTime) {}

So if both are false it returns undefined, moving the footerEl creation statement outside the if seems to fix it.

**Comment by yiminghe** [comment]
thanks for your report
