### ISSUE TITLE
how to do npm publish for the forked version?

### ISSUE THREAD

**Issue by qingbolove** [react-component/calendar#364]
I want to add some external feature of ant-design, so I forked a version of antd, and want to use my forked repo. The problem is that if I install the forked tarball package, it got all the file path same with the source code.
I realized that it is because there may be a publish script, which change the source code to lib file. So I need to publish my fork repo and then install it to get a same "npm install rc-calendar" result. 

Could you please tell me the process to do publish for this package?
 
 I think many other user may want to do fork, and this is a blocking issue that we cannot use our forked repo. Thanks so much!

**Comment by yesmeck** [comment]
```bash
$ npm run compile
$ npm publish
```
