### ISSUE TITLE
没有value的时候会与本地时间慢16小时

### ISSUE THREAD

**Issue by cy20006** [react-component/calendar#38]
没有value的时候会与本地时间慢16小时
![image](https://cloud.githubusercontent.com/assets/3981024/8373968/138a9384-1c24-11e5-8e91-432f5ffb8607.png)

**Comment by cy20006** [comment]
Date.now()我这获取的是本地时间戳

**Comment by yiminghe** [comment]
默认时区不是中国，请设置 value

**Comment by Grifree** [comment]
[help] 请问如何配置更改默认时区?

**Comment by Grifree** [comment]
[help] 请问如何配置更改默认时区? @yiminghe

**Comment by benjycui** [comment]
google moment-timezone
