### ISSUE TITLE
picker 容器的 className 丢失了

### ISSUE THREAD

**Issue by afc163** [react-component/calendar#68]
4.0.0-alpha8

现在：

![](https://t.alipayobjects.com/images/rmsweb/T1aD4iXbxaXXXXXXXX.png)

原来：

![](https://t.alipayobjects.com/images/rmsweb/T1d9JiXf4fXXXXXXXX.png)

**Comment by afc163** [comment]
picker 的类貌似加到浮层上去了。

**Comment by yiminghe** [comment]
不兼容修改。没有容器，需要的话自己设置

popup 的 父节点不重要，popup 跟节点叫 picker

**Comment by afc163** [comment]
已自行包裹。
