### ISSUE TITLE
select new month with value

### ISSUE THREAD

**Issue by wmoulin** [react-component/calendar#71]
Hi,

When i pass a value to the calendar, the componant is not redraw when i want select a new mont or year, it's cause by the setValue method in calendarMixin, the state don't change.

there is another way to do this ?

**Comment by yiminghe** [comment]
you may want to pass defaultValue. or you have to listen onChange

see controlled component https://facebook.github.io/react/docs/forms.html

**Comment by wmoulin** [comment]
Thanks, it's ok with the defaultValue.

I would to know if you have planned some developments for catching keyEvent
in month and year selection panel or to pass a local for the monthFormater
in CalendarHeader.

2015-11-04 11:15 GMT+01:00 yiminghe <notifications@github.com>:

**Comment by yiminghe** [comment]
1. keyEvent in month and year is not urgent now, welcome pr.

2. monthFormat already passed: https://github.com/react-component/calendar/blob/84c7f3692bed2bd93b4118ca407e4e5eef32bfca/src/calendar/CalendarHeader.jsx#L37

**Comment by wmoulin** [comment]
I agree, the pattern is passed but if i would to change the month label
switch lang, i should passed the local, like this :
this.monthFormatter = new DateTimeFormat(props.locale.monthFormat, props.
locale);

for get locale.months[value] in formatField of DateTimeFormat :
https://github.com/yiminghe/gregorian-calendar-format/blob/master/src/gregorian-calendar-format.js#L382


2015-11-04 14:24 GMT+01:00 yiminghe <notifications@github.com>:

**Comment by yiminghe** [comment]
just change locale prop: https://github.com/react-component/calendar/blob/84c7f3692bed2bd93b4118ca407e4e5eef32bfca/src/calendar/CalendarHeader.jsx#L46

**Comment by wmoulin** [comment]
It don't work for me. I tested with with your locale file 'zh-cn.js' like
your sample
http://react-component.github.io/calendar/examples/antd-calendar.html
I only changed the monthFormat to 'MMMM' but the month link generated in
getMonthYearElement method (
https://github.com/react-component/calendar/blob/master/src/calendar/CalendarHeader.jsx#L75)
is 'Novemeber' and i expected '十一月'

**Comment by yiminghe** [comment]
嗯，是有问题，必须直接传 DateTimeFormat 类型:

http://react-component.github.io/calendar/examples/antd-calendar.html

**Comment by wmoulin** [comment]
what do you mean ?


I can pass the DateTimeFormat to the calendar ?

2015-11-05 10:13 GMT+01:00 yiminghe <notifications@github.com>:

**Comment by yiminghe** [comment]
Yes, 4.0.0-alpha11 allows you pass a DateTimeFormat type directly. 

Refresh and see:

http://react-component.github.io/calendar/examples/antd-calendar.html

**Comment by wmoulin** [comment]
I had not seen the new version, it works with that one.

Thanks for this evolution.

2015-11-05 12:37 GMT+01:00 yiminghe <notifications@github.com>:
