### ISSUE TITLE
I was trying to raise PR   to add locale (ga_IE) but its gives error  as en_US Based

### ISSUE THREAD

**Issue by AbhijeetGaware** [react-component/calendar#713]
i need to add locale for irish so i tried to many times i am having issue with those error
evrything is accurate but stuck with those error 
<img width="601" alt="Screenshot 2020-06-06 at 2 00 06 PM" src="https://user-images.githubusercontent.com/56472463/83939938-69fde480-a7fe-11ea-8eda-533fda444791.png">

<img width="660" alt="Screenshot 2020-06-06 at 1 59 16 PM" src="https://user-images.githubusercontent.com/56472463/83939928-55b9e780-a7fe-11ea-826d-f3472b306552.png">

**Comment by AbhijeetGaware** [comment]
https://github.com/ant-design/ant-design/pull/24769

**Comment by yoyo837** [comment]
Please provide a copy of the `ga_IE` locale file, let me have a try.
