### ISSUE TITLE
Next/Prev month, Next / Last year button is not working for controlled component

### ISSUE THREAD

**Issue by gogo1211** [react-component/calendar#839]
Hi, hope you are doing great.

I tried to use rc-calendar as following.
 ```
const [date, setDate] = useState(null)
....
<Calendar
  className="calendar"
  disabledDate={disableDate}
  showDateInput={false}
  showToday={false}
  showOk={false}
  value={date}
  onSelect={setDate}
/>
```
In this case, the month/year control buttons are not working. If I remove **value={date}**, then it works again.

Hope to hear from you soon.

Best

**Comment by xrkffgg** [comment]
https://github.com/react-component/calendar/blob/46a444449d2e3dc8077bc68a5f070a6dd2a9e36e/src/Calendar.jsx#L24

value should use `moment` type

**Comment by gogo1211** [comment]
Thanks for the quick update, @xrkffgg 

Just tried this but still the same.

`const [date, setDate] = useState(moment())`

**Comment by gogo1211** [comment]
@xrkffgg 
Please try this one. https://codesandbox.io/s/confident-cdn-ub7qq

**Comment by xrkffgg** [comment]
calendar haven't maintained it for a long time

Try https://github.com/react-component/picker

**Comment by gogo1211** [comment]
Will try. Thank you very much, @xrkffgg
