### ISSUE TITLE
I can select month or year after changing value outside

### ISSUE THREAD

**Issue by wp2123** [react-component/calendar#89]
I want to change value with other function. So I change the date passed to the Calendar which used as props value.
The problem is that I can't select month and year anymore on Calendar after I changed the value passed to the Calendar.

**Comment by yiminghe** [comment]
If you pass value, you need to listen onChange to sync value.

**Comment by wp2123** [comment]
👍
Now I bind the value with a state.date and set the state.date when I need to change selected time.
