### ISSUE TITLE
value is undefined

### ISSUE THREAD

**Issue by jsers** [react-component/calendar#94]
https://github.com/react-component/calendar/blob/master/src/Picker.jsx#L58
value 重置为undefined 时候就会渲染旧的state.value了

**Comment by benjycui** [comment]
设为 `null` 就会清空现在的值。

**Comment by jsers** [comment]
看过源码后明白设置为 `null` 是可以，但是初次用 设置为 `undefined` 就会感觉莫名其妙。  
觉得是否可以考虑优化下

**Comment by benjycui** [comment]
See: http://demo.alibaba-inc.com/categories/1977/projects/17165

觉得 antd 和 rc 也需要统一下 `undefined` 和 `null` 的语义。

**Comment by benjycui** [comment]
See: https://github.com/facebook/react/issues/2166#issuecomment-55040147

觉得 antd 和 rc 也需要统一下 `undefined` 和 `null` 的语义。
