### ISSUE TITLE
DatePicker rendering Calendar in <body> causes  position and aligning prolems

### ISSUE THREAD

**Issue by Alexoner** [react-component/calendar#95]
When using a modal which contains a DatePicker,the calendar's default position is not so nice.It will be under the modal.And after setting larger zIndex of DatePicker component,we can have it on modal, but giving rise to a "alignment while scrolling" issue.The Calendar component doesn't adhere to modal component.
  I noticed that there is an API controlling the alignment of Calendar, which involves complex configuration.
Maybe putting ```<div class="rc-calendar-picker">``` inside its direct parent instead of distant ancestor will make it easier to use.

**Comment by yiminghe** [comment]
getCalendarContainer will give you more control:
http://react-component.github.io/calendar/examples/getCalendarContainer.html

**Comment by Alexoner** [comment]
It works, thanks!
