### ISSUE TITLE
Add react peer dependency

### ISSUE THREAD

**Issue by tolmasky** [react-component/calendar#97]
Currently tonic doesn't automatically include react with this because React is not listed as a peer dependency, if it were, you'd get the same behavior as react-image-grid for example https://tonicdev.com/npm/react-image-grid . As such, users get a "React missing" error when they try it: https://tonicdev.com/npm/rc-calendar .

**Comment by moreJs** [comment]
+1

**Comment by yiminghe** [comment]
React should be dependent by application code, and npm3 will no longer install peerDependencies

**Comment by tolmasky** [comment]
Yes, the point is that npm 3 WILL warn you if you haven't included it (that is the purpose of peer dependencies, to explicitly state that the application should have the package as a dependency). If not, you'll never know that until you get a "module not found" error when you run it.

Similarly, tonicdev.com will appropriately include it as well. For example, look at react-image-grid: https://tonicdev.com/npm/react-image-grid . It does the appropriate thing of requiring react (which the user can then change to whatever version they want). If not, this library will continue to break when users click on "Try it browser" on npm: http://npmjs.com/rc-calendar since there is no way to know that react is need.

**Comment by yiminghe** [comment]
Ok, this make sense.
